os: linux
dist: xenial
language: c
compiler: gcc
services:
- docker
before_install:
- docker pull gcc:7.5.0

install:
- docker build -t testcicd .

script:
- docker run -t testcicd

deploy:
  - provider: script
    script: bash "$TRAVIS_BUILD_DIR/scripts/docker_push.sh"
    on:
      repo: daltonkell/test-cicd
      branch: master
      tags: true
